### ISSUE TITLE
what version of UI will work with api v3?

### ISSUE THREAD

**Issue by WaysonWei** [staart/api#1486]
Hi, Anand. Just wondering which version of Staart UI will work with the latest version of API v3? We can't wait to try this out.Thanks.

**Comment by AnandChowdhary** [comment]
Glad to hear that you're exciting about trying v3 out! You can already start using API v3, and it'll work perfectly with the v3 branch of staart/ui: https://github.com/staart/ui/tree/v3 (this time written in Svelte rather than Vue.js, using Sapper rather than Nuxt.js). This is also expected to be merged shortly. 😄
