### ISSUE TITLE
demo ?

### ISSUE THREAD

**Issue by blondie63** [staart/api#1648]
Without any controversy, but having both demos not working is not a great business card ..

**Comment by AnandChowdhary** [comment]
Haha for sure, I totally understand! I've been working on the new versions of both, so the UI is not live. But about the API: I always get a server but then end up not renewing it, since Node.js apps cannot run on traditional shared hosting accounts, so...

> Without any controversy, but having both demos not working is not a great business card...

Please feel free to sponsor a $5/m DigitalOcean droplet for the API demo! 😉

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
