### ISSUE TITLE
Issues with Security Features

### ISSUE THREAD

**Issue by mattp95** [staart/api#331]
Hi there,
Thank you for all your work so far on this project.

I have come across a few issues with some security features that are included not functioning. 
For example;

IP address restrictions  - These are not actually restricting access to specified IP ranges (For example on the team view).
Invalidate session - Does not seem to 'log you out of this session in the next few minutes'.

The view for editing a users permissions with relation to a team also seems to not exist. Has anyone else come across these issues? If not I will examine in further detail and submit a PR for fixes, but I don't want to waste time if this is a known issue and someone else is working on a fix or it is a common config issue my side.

**Comment by AnandChowdhary** [comment]
Hi @mattp95, thanks for opening this issue!

I haven't tested IP whitelisting in the live version right now, but the logic is available [here in `jwt.ts`](https://github.com/o15y/staart/blob/master/src/helpers/jwt.ts#L278) and it's used in the middleware [here](https://github.com/o15y/staart/blob/master/src/helpers/middleware.ts#L129). It seems like this is only in the API key right now, not users, so I'll make sure I add it there too.

I think it's best to add the IP check when on the organization settings/dashboard, but not the user. Since a user can be part of multiple organizations, they should still be able to edit their profile, change their password, etc., from any IP address, and only be restricted to an IP/CIDR range when they're in their organization.

I'll also have a closer look at the invalidation token. How it works right now is using Redis. The logic for that is available [here in `jwt.ts`](https://github.com/o15y/staart/blob/master/src/helpers/jwt.ts#L250). Maybe it could be something to do with your Redis configuration that it's not saving it? Maybe it just doesn't work. I'll have a look. 😄

**Comment by mattpi-NSL** [comment]
Thank you for this. In this case is removing the IP restriction view in users from staart-ui a reasonable plan? If a user should always be able to login to thier own account it might remove some confusion.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
