### ISSUE TITLE
Use ObjectionJS + Knex.js for SQL

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#971]
Instead of querying, using entities and TypeORM

**Comment by simoami** [comment]
Hi @AnandChowdhary 
Have you done any comparative research on this? Are you locked-in with TypeORM?

I worked with [ObjectionJS](https://vincit.github.io/objection.js/) / [Knex](http://knexjs.org/) in one of my projects and it's very flexible. Here's why I think it would be relevant to the project:
- Has good support for TS projects. Includes typings.
- Migration scripts are very easy compared to TypeORM equivalent. I briefly looked at TypeORM. Here's some examples for this project
```ts
export async function up(knex: Knex): Promise<any> {
  await knex.schema.createTable(TABLES.DOMAINS, table => {
    table.increments().primary()
    table.integer('organizationId').references('id').inTable(TABLES.ORGANIZATIONS).onDelete('CASCADE')
    table.string('domain', 255).notNullable()
    table.string('verificationCode', 255)
    table.boolean('isVerified').defaultTo(false).notNullable()
    table.timestamp('createdAt').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updatedAt')
  })
  await knex.schema.createTable(TABLES.BACKUP_CODES, table => {
    table.integer('code').unsigned().primary()
    table.boolean('used').defaultTo(false)
    table.integer('userId').references('id').inTable(TABLES.USERS).onDelete('CASCADE')
    table.timestamp('createdAt').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updatedAt')
  })
  await knex.schema.createTable(TABLES.EMAILS, table => {
    table.increments().primary()
    table.string('email').notNullable()
    table.boolean('isVerified').defaultTo(false)
    table.integer('userId').references('id').inTable(TABLES.USERS).onDelete('CASCADE')
    table.timestamp('createdAt').defaultTo(knex.fn.now()).notNullable()
    table.timestamp('updatedAt')
  })
  
  // other table schemas
}
``` 
Notice that I used camel case for the column names, but Knex offers a `knexSnakeCaseMappers` to convert any table/column name or foreign relation or constraint to snake_case in the db layer.
- ObjectionJS models 
  - can be a complete replacement for your crud layer. You can augment them with methods
  - have lifecycle methods to automatically populate createdAt/updatedAt, so you don't need to manually do that in every operation. 
  - Has useful plugins! For example `objection-visibility` allows you to hide secret props you don't want to show during json deserialization. So instead of methods like`deleteSensitiveInfoUser`you simply add this line in `models/User.js`
```
public static hidden = ['password', 'twoFactorSecret']
```
  - you can also use `objection-hashid` to auto convert numeric ids to hashids or create a BaseModel that transforms ids and foreign keys for you. Specifically because this plugin doesn't support the hashId prefix you use in the code.
  - Models have their own json schema validation, so another layer of data validation.
- Knex is an awesome query builder that can support complex and raw query operations. The onDelete('CASCADE') shown in the table schema above will delete the dependent records so you don't have to manually handle dependencies, like you have in organizations.ts:
```
    await deleteOrganization(organizationId);
    await deleteAllOrganizationMemberships(organizationId); // <-- this won't be necessary because of the ON DELETE CASCADE constraint
```
- Many of the custom query operations like `getUserByUsername` become `User.query().findOne({ username })`

If this all sounds appealing to you :) and decide to proceed this route, I offer to help you setup the migration scripts and npm scripts to migration, rollback and create new migration files.

**Comment by AnandChowdhary** [comment]
Thanks for your hard work, @simoami! You seems to know more than me and I'm convinced! Let's use Objection.js instead of TypeORM. All I care about is first-class TypeScript support:

```ts
const person = await Person.query().findById(1); // This is of type "Person"
console.log(person.firstName); // This is of type "string"
```

Would love your help in the initial setup, and however much you'd be interested in taking up for the migration. :)

**Comment by simoami** [comment]
Thanks @AnandChowdhary. I'll start looking into it over the weekend!

**Comment by harrytran998** [comment]
Thank you for your team's efforts, @AnandChowdhary . I and my friends will look for your project! Especially this!

**Comment by AnandChowdhary** [comment]
In v2, we're now using [Prisma](https://github.com/prisma/prisma).

**Comment by simoami** [comment]
Awesome @AnandChowdhary! Glad you got to it! Prisma looks interesting.
